os: linux

language: c

sudo: required
dist: trusty

apt:
        packages:
                - gcc-multilib
                - g++-multilib
                
script: 
        - ./contrib/download_prerequisites 
        - ./configure 
        - make --silent > make.log

notifications:
        email:
                recipients:
                        - danielprokopp2@gmail.com
                on_success: always
                on_failure: always
