os: linux

language: c

sudo: required
dist: trusty

before_script:
        - sudo apt-get install gcc-multilib -y
        - sudo apt-get install g++-multilib -y
script: 
        - ./contrib/download_prerequisites 
        - ./configure 
        - make -j5 --silent > make.log

notifications:
        email:
                recipients:
                        - danielprokopp2@gmail.com
                on_success: always
                on_failure: always
