os: linux

language: c

sudo: required
dist: trusty

before_script:
        sudo apt-get install gcc-multilib g++-multilib -y

script: 
        ./contrib/download_prerequisites && ./configure && make --silent

notifications:
        email:
                recipients:
                        - danielprokopp2@gmail.com
                on_success: always
                on_failure: always
